"""TickEngine — one virtual day per step(). Drives rules + agents."""

from __future__ import annotations

import random
from dataclasses import dataclass

from living_world.core.event import LegendEvent
from living_world.core.world import World
from living_world.memory.memory_store import AgentMemoryStore
from living_world.persistence import Repository
from living_world.agents.chronicler import Chronicler
from living_world.agents.conscience import ConsciousnessLayer
from living_world.agents.dialogue import DialogueGenerator
from living_world.agents.emergent import EmergentEventProposer
from living_world.agents.narrator import Narrator
from living_world.agents.perception import SubjectivePerception
from living_world.agents.planner import AgentPlanner
from living_world.agents.self_update import AgentSelfUpdate
from living_world.rules.consequences import ConsequenceEngine
from living_world.rules.historical_figures import HistoricalFigureRegistry
from living_world.rules.interactions import InteractionEngine
from living_world.rules.movement import MovementPolicy
from living_world.rules.resolver import EventResolver
from living_world.rules.storyteller import TileStoryteller
from living_world.tick_logger import TickLogger
from living_world.world_pack import WorldPack


@dataclass
class TickStats:
    tick: int
    proposals: int = 0
    events_realized: int = 0
    spotlight_candidates: int = 0
    promotions: int = 0
    movements: int = 0
    reactions: int = 0      # events generated by consequence chain
    tier1: int = 0
    tier3: int = 0


class TickEngine:
    """Glues rules + agents + memory + persistence into one tick loop."""

    def __init__(
        self,
        world: World,
        packs: list[WorldPack],
        seed: int = 42,
        narrator: Narrator | None = None,
        repository: Repository | None = None,
        memory: AgentMemoryStore | None = None,
        snapshot_every_ticks: int = 10,
        reflect_every_ticks: int = 7,
    ) -> None:
        self.world = world
        self.packs = {p.pack_id: p for p in packs}
        self.rng = random.Random(seed)
        self.resolver = EventResolver(world, random.Random(seed + 1))
        self.consciousness: ConsciousnessLayer | None = None  # wired by factory
        self.hf_registry = HistoricalFigureRegistry(world)
        self.movement = MovementPolicy(world, random.Random(seed + 2))
        self.interactions = InteractionEngine(world, random.Random(seed + 3))
        self.consequences = ConsequenceEngine(world, random.Random(seed + 4))
        self.narrator = narrator or Narrator()
        self.repository = repository
        self.memory = memory
        self.snapshot_every_ticks = snapshot_every_ticks
        self.reflect_every_ticks = reflect_every_ticks
        self.tick_logger: TickLogger | None = None
        self.agent_planner: AgentPlanner | None = None
        self.plan_every_ticks: int = 7
        self.plan_hf_only: bool = True
        # A→B dialogue turn that mutates affinity + beliefs.
        # Factory sets dialogue_generator + conversation_loop_enabled.
        self.dialogue_generator: DialogueGenerator | None = None
        self.conversation_loop_enabled: bool = False
        # Chronicler (说书人) — observes, never steers.
        self.chronicler: Chronicler | None = None
        self.chronicle_every_ticks: int = 14
        self._last_chronicle_tick: int = 0
        # Emergent event proposer — LLM invents novel events on hot tiles.
        self.emergent_proposer: EmergentEventProposer | None = None
        self.emergent_max_per_tick: int = 2
        # Subjective perception: rewrite events from each participant's POV
        # before storing in memory. Only fires for important events to keep
        # cost bounded (1 LLM call per participant per important event).
        self.perception: SubjectivePerception | None = None
        self.perception_threshold: float = 0.5
        # AgentSelfUpdate: after important events, LLM speaks AS the
        # participant and reports how their inner state shifted (attributes,
        # needs, emotions, beliefs, goal, motivations, reflection).
        self.self_update: AgentSelfUpdate | None = None
        self.self_update_threshold: float = 0.5

        # Pipeline of phases for step(). Importable + swappable; see phases.py.
        # Defaults to the canonical 13-stage pipeline. Tests / experiments can
        # do `engine.pipeline = [DecayPhase(), MovementPhase()]` to isolate
        # behaviour or `engine.pipeline.insert(0, MyInboxPhase())` to extend.
        from living_world.phases import DEFAULT_PIPELINE
        self.pipeline = list(DEFAULT_PIPELINE)
        # Per-phase latency history for telemetry / lw smoke perf table
        self.phase_latency: dict[str, list[float]] = {}
        # Events realized in current tick — populated by _process_event,
        # consumed by deferred PerceptionPhase + SelfUpdatePhase. Cleared
        # at start of each step().
        self._tick_events: list[LegendEvent] = []

        # one storyteller per tile, using its primary pack's storyteller config
        self.storytellers: dict[str, TileStoryteller] = {}
        for tile in world.all_tiles():
            pack = self.packs.get(tile.primary_pack)
            if pack is None:
                continue
            self.storytellers[tile.tile_id] = TileStoryteller(
                tile=tile,
                config=pack.manifest.storyteller,
                event_pool=pack.events,
                rng=random.Random(seed ^ hash(tile.tile_id)),
            )

    def _event_template(self, pack_id: str, kind: str):
        pack = self.packs.get(pack_id)
        if pack is None:
            return None
        return pack.events.get(kind)

    def _process_event(self, event: LegendEvent, stats: TickStats) -> None:
        """Unified event pipeline: enhance → record → persist → promote → memory → consequences."""
        t = self.world.current_tick
        log = self.tick_logger

        # Tier routing
        self.narrator.enhance(event)
        if log:
            tier_method = "template"
            if event.tier_used == 2:
                tier_method = "llm-rewrite"
            elif event.tier_used == 3:
                tier_method = "llm-dialogue"
            log.tier_routing(event.event_id, event.tier_used, tier_method)

        # Record
        self.world.record_event(event)
        stats.events_realized += 1
        if event.importance >= 0.6:
            stats.spotlight_candidates += 1

        # Persist
        if self.repository is not None:
            try:
                self.repository.append_event(event)
            except Exception as exc:  # noqa: BLE001
                print(f"[persist] append_event failed: {exc}")

        # Promote historical figures
        promoted = self.hf_registry.observe_event(event)
        stats.promotions += len(promoted)
        if log:
            for agent_id in promoted:
                log.promotion(agent_id, f"observed {event.event_kind}")

        # ── CONSEQUENCES: stat changes + rare description mutations ──
        # No recursion — changes persist on agents, next tick reacts naturally.
        for reaction in self.consequences.apply(event):
            self.narrator.enhance(reaction)
            self.world.record_event(reaction)
            stats.reactions += 1
            if reaction.importance >= 0.6:
                stats.spotlight_candidates += 1
            self.hf_registry.observe_event(reaction)
            self._tick_events.append(reaction)
            if log:
                changes = ", ".join(f"{k}:{v}" for d in reaction.stat_changes.values() for k, v in d.items())
                for aid in reaction.participants:
                    log.consequence(reaction.event_kind, aid, changes or "mutation")

        # Track this event for batched perception + self_update at end of tick.
        # See PerceptionPhase / SelfUpdatePhase in phases.py — deferring lets
        # us gather() ALL events' participants in one async batch instead of
        # blocking per-event.
        self._tick_events.append(event)

        # ── Dialogue loop: A→B reaction mutates affinity + beliefs ──
        # For Tier-3 events with exactly two participants, ask the LLM to
        # generate the listener's in-character reaction (reply + affinity
        # delta + optional belief update). This is the one place where LLM
        # output mutates game state rather than just narrative.
        if (
            self.conversation_loop_enabled
            and event.tier_used >= 2
            and len(event.participants) == 2
            and self.dialogue_generator is not None
        ):
            speaker = self.world.get_agent(event.participants[0])
            listener = self.world.get_agent(event.participants[1])
            if speaker is not None and listener is not None and listener.is_alive():
                try:
                    reaction = self.dialogue_generator.conversation_turn(
                        speaker, listener, event, self.world, memory_store=self.memory,
                    )
                except Exception:
                    reaction = None
                if reaction:
                    delta = int(reaction.get("affinity_delta", 0) or 0)
                    belief = reaction.get("belief_update")
                    if delta:
                        listener.adjust_affinity(speaker.agent_id, delta, t)
                    if isinstance(belief, str) and belief.strip():
                        listener.set_belief(speaker.agent_id, belief)
                        if log:
                            log.belief_updated(listener.agent_id, speaker.agent_id, belief)
                    if log:
                        log.dialogue_reaction(
                            listener.agent_id, speaker.agent_id,
                            delta, reaction.get("reply", ""), belief,
                        )

        # ── Mark plans stale when reality disrupts them (re-plans next tick) ──
        # High-importance events invalidate the involved agents' plans; they
        # re-plan at the START of the next tick instead of waiting a week.
        if self.agent_planner is not None and event.importance >= 0.4:
            for aid in event.participants:
                agent = self.world.get_agent(aid)
                if agent is not None and agent.is_alive():
                    agent.state_extra["plan_stale"] = True
            # If someone's "seek" target just died, their plan is stale too.
            if event.outcome == "failure" or "death" in event.event_kind.lower():
                dead_ids = set(event.participants)
                for a in self.world.living_agents():
                    plan = a.get_weekly_plan() if hasattr(a, "get_weekly_plan") else {}
                    seek = plan.get("seek") if isinstance(plan, dict) else None
                    if isinstance(seek, list) and any(
                        any(d in str(s).lower() for d in dead_ids) for s in seek
                    ):
                        a.state_extra["plan_stale"] = True

    def _replan_stale_agents(self, t: int) -> int:
        """Regenerate weekly plans for agents marked stale by recent events."""
        if self.agent_planner is None:
            return 0
        count = 0
        for agent in list(self.world.living_agents()):
            if not agent.state_extra.get("plan_stale"):
                continue
            if self.plan_hf_only and not agent.is_historical_figure:
                agent.state_extra["plan_stale"] = False
                continue
            plan = self.agent_planner.plan_for_agent(agent, self.world, self.memory)
            if plan:
                agent.state_extra["weekly_plan"] = plan
                agent.state_extra["weekly_plan_tick"] = t
                if self.tick_logger:
                    self.tick_logger.plan_generated(agent.agent_id, plan)
                count += 1
            agent.state_extra["plan_stale"] = False
        return count

    def step(self) -> TickStats:
        """One virtual day. The 13-stage pipeline lives in `phases.py`;
        this method just drives it. To customise, swap `self.pipeline`
        before calling `step()` (insert/remove/reorder phases freely).

        Each phase is timed and aggregated into `self.phase_latency`
        (rolling list of seconds per phase name). `lw smoke` surfaces a
        latency table at the end so you can see WHERE time goes —
        prerequisite for any future optimisation.
        """
        import time as _time
        self.world.current_tick += 1
        t = self.world.current_tick
        stats = TickStats(tick=t)
        log = self.tick_logger
        # Reset per-tick event accumulator (consumed by deferred phases).
        self._tick_events = []

        if log:
            log.tick_start(t)

        for phase in self.pipeline:
            t0 = _time.time()
            try:
                phase.run(self, t, stats)
            except Exception as exc:  # noqa: BLE001 — phase isolation
                if log and hasattr(log, "phase_error"):
                    log.phase_error(phase.name, exc)
                else:
                    print(f"[phase {phase.name}] error: {exc!r}")
            # Tolerate stub engines (in tests) that don't carry phase_latency.
            if hasattr(self, "phase_latency"):
                self.phase_latency.setdefault(phase.name, []).append(_time.time() - t0)

        stats.tier1 = self.narrator.stats.tier1
        stats.tier3 = self.narrator.stats.tier3

        if log:
            log.tick_end(t, stats)

        return stats

    def run(self, days: int) -> list[TickStats]:
        return [self.step() for _ in range(days)]
