/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent */
        get: operations["agent_api_agent__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap */
        post: operations["bootstrap_api_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chronicle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chronicle */
        get: operations["chronicle_api_chronicle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chronicle.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chronicle Md */
        get: operations["chronicle_md_api_chronicle_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event_kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Kinds */
        get: operations["event_kinds_api_event_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feature_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Features */
        get: operations["features_api_feature_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packs_available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Packs Available */
        get: operations["packs_available_api_packs_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personas
         * @description Expose loaded YAML personas per pack — for Library 'Characters' tab.
         *
         *     These are the AUTHORED set, not just the spawned ones. Useful when
         *     you want to see "who could appear" vs "who's currently in the run".
         */
        get: operations["personas_api_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Drop the loaded world. The frontend should then re-call
         *     /api/bootstrap with the desired packs.
         */
        post: operations["reset_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings Get
         * @description Settings shape is deep + dynamic — exposed as open dict for now.
         *     Typing it is a follow-up (one Pydantic model per section).
         */
        get: operations["settings_get_api_settings_get"];
        put?: never;
        /**
         * Settings Set
         * @description Patch the live settings + persist to settings.yaml.
         *
         *     Accepts a partial dict — only top-level sections present in the
         *     payload are merged. Returns the merged settings dict.
         *
         *     NOTE: Most settings only take effect on next bootstrap (engine
         *     is built from settings at bootstrap time). Caller should
         *     prompt the user to Reset → Simulate again after important
         *     changes (model swap, packs, feature flags).
         */
        post: operations["settings_set_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social_graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social Graph
         * @description Lightweight projection for client-side social-metrics compute.
         *
         *     Returns just (agentId, packId, alive, relationships) — exactly
         *     what `@living-world/sim-core` `computeSocialMetrics` consumes.
         *     Keeping the heavy computation client-side proves the TS port is
         *     a real consumer (not just an isomorphic re-implementation
         *     sitting unused). Server stays a thin data tap.
         */
        get: operations["social_graph_api_social_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Templates
         * @description Expose loaded event TEMPLATES per pack — for Library 'Stories' tab.
         */
        get: operations["templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tick */
        post: operations["tick_api_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiles */
        get: operations["tiles_api_tiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** World */
        get: operations["world_api_world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Agent */
        Agent: {
            /** Alignment */
            alignment: string;
            /** Alive */
            alive: boolean;
            /** Attributes */
            attributes?: {
                [key: string]: number | string;
            } | null;
            /** Beliefs */
            beliefs?: {
                [key: string]: string;
            } | null;
            /** Emotions */
            emotions?: {
                [key: string]: number;
            } | null;
            /** Goal */
            goal?: string | null;
            /** Id */
            id: string;
            /** Ishf */
            isHf: boolean;
            /** Motivations */
            motivations?: string[] | null;
            /** Name */
            name: string;
            /** Needs */
            needs?: {
                [key: string]: number;
            } | null;
            /** Pack */
            pack: string;
            /** Persona */
            persona?: string | null;
            /** Recentevents */
            recentEvents?: components["schemas"]["WorldEvent"][] | null;
            /** Relationships */
            relationships?: components["schemas"]["Relationship"][] | null;
            /** Tags */
            tags: string[];
            /** Tile */
            tile: string;
            /** Weeklyplan */
            weeklyPlan?: {
                [key: string]: string[];
            } | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** BootstrapBody */
        BootstrapBody: {
            /** Packs */
            packs: string[];
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** Chapter */
        Chapter: {
            /** Body */
            body: string;
            /** Event Ids */
            event_ids: string[];
            /** Pack Id */
            pack_id: string;
            /** Tick */
            tick: number;
            /** Title */
            title: string;
        };
        /** ChronicleMarkdown */
        ChronicleMarkdown: {
            /** Markdown */
            markdown: string;
        };
        /** DiversitySummary */
        DiversitySummary: {
            /** Top Kind */
            top_kind?: string | null;
            /** Top Pct */
            top_pct: number;
            /** Total */
            total: number;
            /** Unique */
            unique: number;
        };
        /** EventKindCount */
        EventKindCount: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
        };
        /** EventTemplateRow */
        EventTemplateRow: {
            /** Baseimportance */
            baseImportance: number;
            /** Description */
            description: string;
            /** Eventkind */
            eventKind: string;
            /** Pack */
            pack: string;
            /** Source */
            source: string;
        };
        /** FeatureStatus */
        FeatureStatus: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** On */
            on: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Loaded */
            loaded: boolean;
            /** Ok */
            ok: boolean;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** PersonaRow */
        PersonaRow: {
            /** Alignment */
            alignment: string;
            /** Id */
            id: string;
            /** Ishf */
            isHf: boolean;
            /** Name */
            name: string;
            /** Pack */
            pack: string;
            /** Persona */
            persona: string;
            /** Tags */
            tags: string[];
        };
        /** Relationship */
        Relationship: {
            /** Affinity */
            affinity: number;
            /** Kind */
            kind: string;
            /** Target */
            target: string;
        };
        /** SocialAgent */
        SocialAgent: {
            /** Agentid */
            agentId: string;
            /** Alive */
            alive: boolean;
            /** Packid */
            packId: string;
            /** Relationships */
            relationships: components["schemas"]["SocialRelationship"][];
        };
        /** SocialGraph */
        SocialGraph: {
            /** Agents */
            agents: components["schemas"]["SocialAgent"][];
        };
        /** SocialRelationship */
        SocialRelationship: {
            /** Affinity */
            affinity: number;
            /** Targetid */
            targetId: string;
        };
        /** TickBody */
        TickBody: {
            /**
             * N
             * @default 1
             */
            n: number;
        };
        /** Tile */
        Tile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Pack */
            pack: string;
            /** Type */
            type: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorldEvent */
        WorldEvent: {
            /** Id */
            id: string;
            /** Importance */
            importance: number;
            /** Isemergent */
            isEmergent: boolean;
            /** Kind */
            kind: string;
            /** Narrative */
            narrative: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "success" | "failure" | "neutral";
            /** Pack */
            pack: string;
            /** Participants */
            participants: string[];
            /** Tick */
            tick: number;
            /** Tier */
            tier: number;
            /** Tile */
            tile: string;
        };
        /** WorldSnapshot */
        WorldSnapshot: {
            /** Agentsalive */
            agentsAlive: number;
            /** Agentstotal */
            agentsTotal: number;
            /** Chapters */
            chapters: number;
            /** Deaths */
            deaths: number;
            diversity?: components["schemas"]["DiversitySummary"] | null;
            /** Eventstotal */
            eventsTotal: number;
            /** Loaded */
            loaded: boolean;
            /** Modeltier2 */
            modelTier2: string;
            /** Modeltier3 */
            modelTier3: string;
            /** Packs */
            packs: string[];
            /** Tick */
            tick: number;
            /** Tiles */
            tiles: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent_api_agent__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
        };
    };
    bootstrap_api_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chronicle_api_chronicle_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"][];
                };
            };
        };
    };
    chronicle_md_api_chronicle_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChronicleMarkdown"];
                };
            };
        };
    };
    event_kinds_api_event_kinds_get: {
        parameters: {
            query?: {
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventKindCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    features_api_feature_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureStatus"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    packs_available_api_packs_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    personas_api_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaRow"][];
                };
            };
        };
    };
    reset_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    settings_get_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    settings_set_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_graph_api_social_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialGraph"];
                };
            };
        };
    };
    templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTemplateRow"][];
                };
            };
        };
    };
    tick_api_tick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiles_api_tiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tile"][];
                };
            };
        };
    };
    world_api_world_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
        };
    };
}
